MI.WebUI/Controllers/KOController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Dynamic;
using System.Web.Script.Serialization;
using MI.Web.Infrastructure;

namespace MI.WebUI.Controllers
{
    public class KOController : Controller
    {
        //
        // GET: /KO/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Basics()
        {
            return View();
        }

        public ActionResult Collections()
        {
            return View();
        }

        public ActionResult SinglePageWithSammy()
        {
            return View();
        }

        public ActionResult SinglePage()
        {
            return View();
        }
        public ActionResult CustomBindings()
        {
            return View();
        }

      
        [HttpGet]
        public ActionResult mail(string folder)
        {
            dynamic email = new List<dynamic>();

            email.Add(new ExpandoObject());
            email[0].from= "John Smith" + folder;
            email[0].to = "abc@go.com";
            email[0].subject = "This is something urgent";
            email[0].date= "01/01/2010";
            email[0].id =1;

            email.Add(new ExpandoObject());
            email[1].from = "Paris Hilton";
            email[1].to = "xyzc@go.com";
            email[1].subject = "Want my tapes back";
            email[1].date = "06/01/2010";
            email[1].id = 2;
           
            return VidpubJSON(email);
        }

        [HttpGet]
        public ActionResult onemail(string mailId)
        {
            dynamic email = new ExpandoObject();


            email.from = "John Smith : Id:" + mailId.ToString(); ;
            email.to = "abc@go.com";
            email.subject = "This is something urgent";
            email.date = "01/01/2010";
            email.body = "something";
       

            return VidpubJSON(email);
        }

        public ActionResult VidpubJSON(dynamic content)
        {
            var serializer = new JavaScriptSerializer();
            serializer.RegisterConverters(new JavaScriptConverter[] { new ExpandoObjectConverter() });
            var json = serializer.Serialize(content);
            Response.ContentType = "application/json";
            return Content(json);
        }


    }//

    class email
    {
        public string  from { get; set; }
        public string to { get; set; }
        public string subject { get; set; }
        public string date { get; set; }
        
    }
}//

MI.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@Page.Title</title>
   
    @Assets.jQuery(false)
    @Assets.CSS("screen.css")
    @Assets.CSS("print.css", "print")
    @Assets.CSS("forms.css")
    @Assets.CSS("plugins/fancy-type/screen.css")
    @Assets.Script("knockout-2.0.0.js")
    @Assets.Script("knockout.mapping.js")
    @Assets.Script("sammy-latest.min.js")
    

    @*to change theme pass in any of the following theme names: dot-luv, humanity, 
    redmond,start,ui-darkness,ui-lightness,blitzer, dark-hive,eggplant,le-frog
    mint-choc,south-street,trontastic
    *@

    @Assets.jgrid("south-street")
    @Assets.CSS("mi.css")
    @Assets.CSS("menu.css")
</head>
<body>
    <div class="container">
        <div class="span-24">
            <div id="logo">
                <h1>MI</h1>
                    
                <ul id="mainNav">
                    <li><a id="home" href="/">Home</a></li>
                 
                 
                     <li>@Html.ActionLink("Basics", "Basics", "KO")</li>
                     <li>@Html.ActionLink("Lists & Collections", "Collections", "KO")</li>
                     <li>@Html.ActionLink("Single Page", "SinglePage", "KO")</li>
                      <li>@Html.ActionLink("Single Page With Sammy", "SinglePageWithSammy", "KO")</li>
                      <li>@Html.ActionLink("Custom Bindings", "CustomBindings", "KO")</li>
                   
                   
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact us", "About", "Home")</li>
                <!-- end #header -->
            </div>
            <div  id="logindisplay">
            @Html.Partial("_LogOnPartial")
         </div>
           
        </div>
        <hr>
        
        <hr class="space">
        @RenderBody()
        <!--footer---->
        <hr>
        <p>
            @Snippets.FooterText()
        </p>
        <hr>
    </div>
</body>
</html>

MI.WebUI/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}